version: '3.4'
services:
  backend:
    build:
      context: ./backend/
    ports:
      - "9527:5000"
    volumes:
      - "/root/workspace/vsat-pdf-view/database.db:/app/app/database.db"
    restart: always
